trigger:
  - main

pool:
  name: 'Custom Agent'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'Build app'

  - task: Docker@2
    inputs:
      command: build
      dockerfile: Dockerfile
      repository: myapp
      tags: latest
    displayName: 'Build Docker image'
