trigger:
  - main

name: $(Build.DefinitionName)_$(Date:yyyyMMdd)$(Rev:.r)

pool:
  name: 'Custom Agent'

variables:
  buildDir: '$(System.DefaultWorkingDirectory)'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Clean install dependencies'
    workingDirectory: $(buildDir)

  - script: |
      npm run build
    displayName: 'Build project'
    workingDirectory: $(buildDir)

  - task: Cache@2
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
      path: $(buildDir)/node_modules
    displayName: 'Cache npm packages'
