trigger:
  - main

pool:
  name: 'Custom Agent'

variables:
  acrName: 'aakashdemo'
  acrLoginServer: 'myacr.azurecr.io'
  imageName: 'myapp'
  imageTag: 'latest'

steps:
  - checkout: self

  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm ci
      npm run build
    displayName: 'Build app'

  - task: Docker@2
    displayName: 'Login to ACR'
    inputs:
      command: login
      containerRegistry: 'new-service-con-name'  # this must match your service connection name

  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      command: build
      dockerfile: Dockerfile
      repository: $(acrLoginServer)/$(imageName)
      tags: |
        $(imageTag)

  - task: Docker@2
    displayName: 'Push Docker image to ACR'
    inputs:
      command: push
      repository: $(acrLoginServer)/$(imageName)
      tags: |
        $(imageTag)
